### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by sample-text-here**
# yes
Yes yes `yes yes yes` yes. Yes yes yes yes. Yes yes, yes yes yes. Yes yes yes.

- [x] yes
- [x] yes
- [x] yes

### CODE REVIEW

**Comment by sample-text-here** [comment]
yes

**Comment by Arkanic** [comment]
too fast
needs to be slowed down

**Comment by sample-text-here** [comment]
ok, will fix

**Comment by sample-text-here** [comment]
should be ready to merge

**Pull request closed without merging**
